name: "Build and publish Package"
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Publish:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'NORUN')" # Skip the build by adding NORUN in all caps to your commit message
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Publish to NuGet.org
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          dotnet nuget push "bin/Release/Flyingdarts.Shared.*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate --json shield.json
          echo ::set-output name=shield::$(cat shield.json)

      - name: Publish to Shield.io
        uses: JasonEtco/upload-to-release@v1
        with:
          args: |
            --tag-name "v${{ github.run_number }}" 
            --release-id "${{ github.event.repository.releases[0].id }}" 
            --file "shield.json" 
            --name "shield.json"
            --content-type "application/json"